export const rarityGroups: Record<string, string[]> = {
  collectors_rare: ["Collector's Rare", "Cr"],
  common: [
    "Common",
    "Short Print",
    "Duel Terminal Normal Parallel Rare",
    "Duel Terminal Normal Rare Parallel Rare",
  ],
  extra_secret_rare: ["Extra Secret", "Extra Secret Rare"],
  ghost_rare: ["Ghost Rare", "Ghost/Gold Rare"],
  gold_rare: ["Gold Rare"],
  gold_secret_rare: ["Gold Secret Rare"],
  mosaic_rare: ["Mosaic Rare"],
  parallel_rare: ["Normal Parallel Rare"],
  platinum_rare: ["Platinum Rare"],
  platinum_secret_rare: ["Platinum Secret Rare"],
  premium_gold_rare: ["Premium Gold Rare"],
  quarter_century_secret_rare: ["Quarter Century Secret Rare"],
  rare: ["Rare", "Duel Terminal Rare Parallel Rare"],
  secret_parallel_rare: ["Secret Parallel Rare"],
  secret_rare: ["Secret Rare", "Prismatic Secret Rare"],
  shatterfoil: ["Shatterfoil Rare"],
  special: ["10000 Secret Rare", "Ultra Secret Rare"],
  starfoil: ["Starfoil", "Starfoil Rare"],
  starlight_rare: ["Starlight Rare"],
  super_parallel_rare: ["Super Parallel Rare"],
  super_rare: ["Super Rare", "Super Short Print", "Duel Terminal Super Parallel Rare"],
  ultimate_rare: ["Ultimate Rare"],
  ultra_parallel_rare: ["Ultra Parallel Rare", "Ultra Rare (Pharaoh's Rare)"],
  ultra_rare: ["Ultra Rare", "Duel Terminal Ultra Parallel Rare"],
  unknown: [
    "New", "2", "3",
    "European debut", "European & Oceanian debut", "Oceanian debut",
    "Reprint", "New artwork",
  ],
};

export const rarityGroupColors: Record<string, string> = {
  collectors_rare:              "",
  common:                       "#030303",
  extra_secret_rare:            "#ff00dd",
  ghost_rare:                   "#ffffff",
  gold_rare:                    "#ddb812",
  gold_secret_rare:             "#ddb812",
  mosaic_rare:                  "#4cd64c",
  parallel_rare:                "#f1c40f",
  platinum_rare:                "#777777",
  platinum_secret_rare:         "#9b59b6",
  premium_gold_rare:            "#ddb812",
  quarter_century_secret_rare:  "#e74c3c",
  rare:                         "#363636",
  secret_parallel_rare:         "#9b59b6",
  secret_rare:                  "#9b59b6",
  shatterfoil:                  "#4cd64c",
  special:                      "#4cd64c",
  starfoil:                     "#4cd64c",
  starlight_rare:               "#ff00dd",
  super_parallel_rare:          "#f1ff6f",
  super_rare:                   "#f1ff6f",
  ultimate_rare:                "#3801ff",
  ultra_parallel_rare:          "#6194e0",
  ultra_rare:                   "#6194e0",
  unknown:                      "#030303",
};

export const rarityGroupIcons: Record<string, string> = {
  collectors_rare:              "/rarities/collectors_rare.png",
  common:                       "/rarities/common.png",
  extra_secret_rare:            "/rarities/extra_secret_rare.png",
  ghost_rare:                   "/rarities/ghost_rare.png",
  gold_rare:                    "/rarities/gold_rare.png",
  gold_secret_rare:             "/rarities/gold_secret_rare.png",
  mosaic_rare:                  "/rarities/mosaic_rare.png",
  parallel_rare:                "/rarities/parallel_rare.png",
  platinum_rare:                "/rarities/platinum_rare.png",
  platinum_secret_rare:         "/rarities/platinum_secret_rare.png",
  premium_gold_rare:            "/rarities/premium_gold_rare.png",
  quarter_century_secret_rare:  "/rarities/quarter_century_secret_rare.png",
  rare:                         "/rarities/rare.png",
  secret_parallel_rare:         "/rarities/secret_parallel_rare.png",
  secret_rare:                  "/rarities/secret_rare.png",
  shatterfoil:                  "/rarities/shatterfoil.png",
  special:                      "/rarities/special.png",
  starfoil:                     "/rarities/starfoil_rare.png",
  starlight_rare:               "/rarities/starlight_rare.png",
  super_parallel_rare:          "/rarities/super_parallel_rare.png",
  super_rare:                   "/rarities/super_rare.png",
  ultimate_rare:                "/rarities/ultimate_rare.png",
  ultra_parallel_rare:          "/rarities/ultra_parallel_rare.png",
  ultra_rare:                   "/rarities/ultra_rare.png",
  unknown:                      "/rarities/token.png",
};
